theme: jekyll-theme-cayman
title: Magic
description: CRUDify your database into HTTP REST endpoints
show_downloads: true
github:
  zip_url: https://github.com/polterguy/magic/releases/latest/download/magic.zip
  tar_url: https://github.com/polterguy/magic/releases/latest/download/magic.tar.gz
