theme: jekyll-theme-cayman
title: Magic
description: Database + Magic == CRUD HTTP REST endpoints
show_downloads: true
google_analytics: UA-147554379-1
github:
  is_project_page: true
  zip_url: https://github.com/polterguy/magic/archive/v5.3.zip
  tar_url: https://github.com/polterguy/magic/archive/v5.3.tar.gz
  repository_url: https://github.com/polterguy/magic
  owner_name: Thomas Hansen
  repository_name: Magic
