theme: jekyll-theme-midnight
title: Magic Cloud
description: An Open Source Application Generator
show_downloads: true
google_analytics: UA-147554379-1
github:
  is_project_page: true
  zip_url: https://github.com/polterguy/magic/archive/v9.1.0.zip
  tar_url: https://github.com/polterguy/magic/archive/v9.1.0.tar.gz
  repository_url: https://github.com/polterguy/magic
  owner_name: Server Gardens
  repository_name: Magic
