theme: jekyll-theme-cayman
title: Magic
description: Create your CRUD Web apps by simply clicking a button
show_downloads: true
google_analytics: UA-147554379-1
github:
  is_project_page: true
  zip_url: https://github.com/polterguy/magic/archive/v5.7.4.zip
  tar_url: https://github.com/polterguy/magic/archive/v5.7.4.tar.gz
  repository_url: https://github.com/polterguy/magic
  owner_name: Server Gardens
  repository_name: Magic
