theme: jekyll-theme-cayman
title: Magic
description: CRUDify your database into HTTP REST endpoints in seconds
show_downloads: true
github:
  is_project_page: true
  zip_url: https://github.com/polterguy/magic/archive/v4.3-BETA.zip
  tar_url: https://github.com/polterguy/magic/archive/v4.3-BETA.tar.gz
  repository_url: https://github.com/polterguy/magic
  owner_name: Thomas Hansen
  repository_name: Magic
