theme: adam-blog-2
title: Magic Cloud
description: Create your Web Apps in seconds!
show_downloads: true
github:
  is_project_page: true
  zip_url: https://github.com/polterguy/magic/archive/v9.5.3.zip
  tar_url: https://github.com/polterguy/magic/archive/v9.5.3.tar.gz
  repository_url: https://github.com/polterguy/magic
  owner_name: ServerGardens
  repository_name: Magic
