theme: jekyll-theme-midnight
title: Magic
description: Create Web apps in 1 SECOND
show_downloads: true
google_analytics: UA-147554379-1
github:
  is_project_page: true
  zip_url: https://github.com/polterguy/magic/archive/v8.9.4-2.zip
  tar_url: https://github.com/polterguy/magic/archive/v8.9.4-2.tar.gz
  repository_url: https://github.com/polterguy/magic
  owner_name: Server Gardens
  repository_name: Magic
