theme: jekyll-theme-midnight
title: Magic Cloud
description: Where the machine creates your code
show_downloads: true
google_analytics: UA-147554379-1
github:
  is_project_page: true
  zip_url: https://github.com/polterguy/magic/archive/v9.5.9.zip
  tar_url: https://github.com/polterguy/magic/archive/v9.5.9.tar.gz
  repository_url: https://github.com/polterguy/magic
  owner_name: ServerGardens
  repository_name: Magic
